--- 
framework: mocha
tier: xsmall
postMerge: 
  pattern: 
    - "test/**/*.spec.js"
postRun: 
  commands: 
    - "node --version"  
preMerge: 
  pattern: 
    - "test/**/*.spec.js"
preRun: 
  commands: 
    - npm ci
 

