--- 
framework: mocha
tier: xsmall
blocklist:
  - "test/**/*.spec.js"
postMerge: 
  pattern: 
    - "test/**/*.spec.js"
postRun: 
  command: 
    - "node --version"  
preMerge: 
  pattern: 
    - "test/**/*.spec.js"
preRun: 
  command: 
    - npm ci



